"""initial schema

Revision ID: 9a87f5d90b91
Revises: 
Create Date: 2026-05-30 19:05:46.865602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a87f5d90b91'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('filter_badwords', sa.Boolean(), nullable=False),
    sa.Column('filter_links', sa.Boolean(), nullable=False),
    sa.Column('filter_media', sa.Boolean(), nullable=False),
    sa.Column('antiflood_enabled', sa.Boolean(), nullable=False),
    sa.Column('captcha_enabled', sa.Boolean(), nullable=False),
    sa.Column('welcome_enabled', sa.Boolean(), nullable=False),
    sa.Column('warn_limit', sa.Integer(), nullable=False),
    sa.Column('mute_minutes', sa.Integer(), nullable=False),
    sa.Column('welcome_text', sa.String(length=1024), nullable=True),
    sa.Column('log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('banned_words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('pattern', sa.String(length=256), nullable=False),
    sa.Column('is_regex', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banned_words_chat_id'), 'banned_words', ['chat_id'], unique=False)
    op.create_table('warnings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warnings_chat_id'), 'warnings', ['chat_id'], unique=False)
    op.create_index(op.f('ix_warnings_user_id'), 'warnings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warnings_user_id'), table_name='warnings')
    op.drop_index(op.f('ix_warnings_chat_id'), table_name='warnings')
    op.drop_table('warnings')
    op.drop_index(op.f('ix_banned_words_chat_id'), table_name='banned_words')
    op.drop_table('banned_words')
    op.drop_table('chats')
    # ### end Alembic commands ###
